//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poketrumps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Battle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Battle()
        {
            this.Rounds = new HashSet<Round>();
        }
    
        public short BattleID { get; set; }
        public Nullable<short> TrainerID1 { get; set; }
        public Nullable<short> TrainerID2 { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual Trainer Trainer1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Round> Rounds { get; set; }
    }
}
