//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poketrumps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friend
    {
        public short TrainerID1 { get; set; }
        public short TrainerID2 { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
    
        public virtual Trainer Trainer { get; set; }
        public virtual Trainer Trainer1 { get; set; }
    }
}
