//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poketrumps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pokemon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pokemon()
        {
            this.TrainerPokemons = new HashSet<TrainerPokemon>();
        }
    
        public short PokemonID { get; set; }
        public string Name { get; set; }
        public short Attack { get; set; }
        public short Defence { get; set; }
        public short SpecialAttack { get; set; }
        public short SpecialDefence { get; set; }
        public short Speed { get; set; }
        public byte[] Image { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TrainerPokemon> TrainerPokemons { get; set; }
    }
}
