//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poketrumps
{
    using System;
    using System.Collections.Generic;
    
    public partial class Round
    {
        public short RoundID { get; set; }
        public short BattleID { get; set; }
        public short TrainerPokemonID { get; set; }
        public short Trainer2PokemonID { get; set; }
        public short FirstTrainerID { get; set; }
        public string StatChosen { get; set; }
        public short WinnerID { get; set; }
    
        public virtual Battle Battle { get; set; }
    }
}
