//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Poketrumps
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_pokemonNEW
    {
        public Nullable<short> PokemonID { get; set; }
        public string Name { get; set; }
        public short Attack { get; set; }
        public short Defence { get; set; }
        public short SpecialAttack { get; set; }
        public short SpecialDefence { get; set; }
        public short Speed { get; set; }
    }
}
